apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-demo-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: auto-demo
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: auto-demo
    spec:
      containers:
      - name: auto-demo-container
        image: shekeriev/k8s-jenkins:%IMAGE-PLACEHOLDER%
        ports:
        - containerPort: 80 
---
apiVersion: v1
kind: Service
metadata:
  name: auto-demo-svc
  labels:
    app: auto-demo
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 31000
    protocol: TCP
  selector:
    app: auto-demo
